### ISSUE TITLE
Long sleep between iteractions

### ISSUE THREAD

**Issue by dvaqueiro** [mac-cain13/daemonizable-command#27]
I use the library to perform task in specific days and then sleep until next day. I can sleep periods of 2-3 days but i detect my command doesnt respect this periods and make iteractions random.

It's something that i doesn't see.

Sorry about my English.

**Comment by mac-cain13** [comment]
If you want to have full control over the moment of execution I would recommend setting up a cronjob. Sleeping that long is unreliable because sleep will also stop when certain signals are send to the process. Cron is exactly made for the thing you want to do; you can tell it exactly when it should execute a certain command and at what interval.

Hope that helps!
